language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.9-dev"  # 3.9 development branch
# command to install dependencies
install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install codecov
  - pip install telepot
  - pip install paho-mqtt
  - pip install configparser
script: pytest  # run tests
after_success:
  - codecov # submit coverage